# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'faqtheEnd' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'AFNetworking'

  # Pods for faqtheEnd

  target 'faqtheEndTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'faqtheEndUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
