# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EventView' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Kingfisher'
  pod 'Alamofire'
  pod 'YYModel'

  # Pods for EventView

  target 'EventViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EventViewUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
