# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FAQTEXT' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'AFNetworking'
  pod 'SVProgressHUD'
  pod 'YYModel'

  # Pods for FAQTEXT

  target 'FAQTEXTTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FAQTEXTUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
